fork = true
chdir = "~"
frame = "transparent"
idle = true
maximized = false
no-multigrid = false
tabs = true
title-hidden = true
vsync = true
wsl = false
system-native-tabs = true

[font]
normal = ["Monaco"]
size = 16.0
