# fix: If you use homebrew install tmux, you should add the following line to your ~/.tmux.conf
set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"

set -g mouse on
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g focus-events on
set -g renumber-windows on
set -g detach-on-destroy off
set -g popup-border-style 'fg=colour240,bg=default'

set -g status-style bg=default,fg=colour240
set -g status-right "%A %m-%d-%Y"
set -g status-keys emacs
setw -g aggressive-resize on

set -g base-index 1
set -g pane-base-index 1

set -sg escape-time 0
set -g repeat-time 600
set -g display-time 2000
set -g history-limit 10000


unbind C-b
set -g prefix C-\;
bind-key C-\; send-prefix

unbind %
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind \\ split-window -v -c "#{pane_current_path}"

unbind [
bind \; copy-mode

unbind r
bind r source-file ~/.tmux.conf

bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5

bind -r m resize-pane -Z

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane 

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'zykowal/Tmux-session-wizard'

bind C-l send-keys 'C-l'
unbind -n C-\\

set -g @session-wizard 'f'
set -g @session-wizard-preview on
set -g @session-wizard-height 60
set -g @session-wizard-width 80

set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'

# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
run '~/.tmux/plugins/tpm/tpm'
