require("core.autocmds")
require("core.diagnostics")
require("core.keymaps")
require("core.options")
require("core.terminal")
require("core.cmdline")

require("core.theme").setup()
require("core.center").setup()
require("core.statusline").setup()
require("core.trailspace").setup()
require("core.bufremove").setup()
require("core.completion").setup()
require("core.jumpchar").setup()
require("core.autopairs").setup()
