require("core.autocmds")
require("core.diagnostics")
require("core.keymaps")
require("core.options")

require("core.theme").setup()
require("core.session").setup()
require("core.terminal").setup()
require("core.center").setup()
require("core.statusline").setup()
require("core.trailspace").setup()
require("core.bufremove").setup()
require("core.jumpchar").setup()
require("core.git").setup()
require("core.marks").setup()
