require("core.autocmds")
require("core.keymaps")
require("core.options")

require("core.theme").setup()
require("core.transparent").setup()
require("core.session").setup()
require("core.terminal").setup()
require("core.center").setup()
require("core.statusline").setup()
require("core.jumpchar").setup()
require("core.marks").setup()
