vim.keymap.set("i", "jk", "<ESC>")
vim.keymap.set("n", "H", "^")
vim.keymap.set("n", "L", "$")
vim.keymap.set("x", "H", "^")
vim.keymap.set("x", "L", "$")

vim.keymap.set("i", "<C-f>", "<Right>", { desc = "Move cursor right" })
vim.keymap.set("i", "<C-b>", "<Left>", { desc = "Move cursor left" })
vim.keymap.set("i", "<C-a>", "<C-o>^", { desc = "Move to beginning of line" })
vim.keymap.set("i", "<C-e>", "<C-o>$", { desc = "Move to end of line" })

vim.keymap.set("v", "<", "<gv", { desc = "Indent left and reselect" })
vim.keymap.set("v", ">", ">gv", { desc = "Indent right and reselect" })
vim.keymap.set("n", "j", "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true, desc = "Move cursor down" })
vim.keymap.set("x", "j", "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true, desc = "Move cursor down" })
vim.keymap.set("n", "k", "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true, desc = "Move cursor up" })
vim.keymap.set("x", "k", "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true, desc = "Move cursor up" })
vim.keymap.set("n", "<leader>w", "<Cmd>w<CR>", { desc = "Save" })
vim.keymap.set("n", "<leader>q", "<Cmd>confirm q<CR>", { desc = "Quit Window" })
vim.keymap.set("n", "<leader>Q", "<Cmd>confirm qall<CR>", { desc = "Exit Window" })
vim.keymap.set("n", "|", "<Cmd>vsplit<CR>", { desc = "Vertical Split" })
vim.keymap.set("n", "\\", "<Cmd>split<CR>", { desc = "Horizontal Split" })

vim.keymap.set("n", "<C-H>", "<C-w>h", { desc = "Move to left split" })
vim.keymap.set("n", "<C-J>", "<C-w>j", { desc = "Move to below split" })
vim.keymap.set("n", "<C-K>", "<C-w>k", { desc = "Move to above split" })
vim.keymap.set("n", "<C-L>", "<C-w>l", { desc = "Move to right split" })
vim.keymap.set("n", "<C-Up>", "<Cmd>resize -2<CR>", { desc = "Resize split up" })
vim.keymap.set("n", "<C-Down>", "<Cmd>resize +2<CR>", { desc = "Resize split down" })
vim.keymap.set("n", "<C-Left>", "<Cmd>vertical resize -2<CR>", { desc = "Resize split left" })
vim.keymap.set("n", "<C-Right>", "<Cmd>vertical resize +2<CR>", { desc = "Resize split right" })

vim.keymap.set("n", "n", "'Nn'[v:searchforward].'zv'", { expr = true, desc = "Next Search Result" })
vim.keymap.set("n", "N", "'nN'[v:searchforward].'zv'", { expr = true, desc = "Prev Search Result" })

vim.keymap.set("v", "p", '"_dP', { noremap = true, silent = true })

vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "Clear search highlight" })
vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })

vim.keymap.set("n", "<leader>;", "q:", { desc = "Command line" })

vim.keymap.set("n", "<C-q>", "<cmd>:copen<CR>", { desc = "Open quickfix list" })
vim.keymap.set("n", "<leader>lq", function() vim.diagnostic.setqflist() end, { desc = "Open qflist" })
vim.keymap.set("n", "<leader>ll", function() vim.diagnostic.setloclist() end, { desc = "Open loclist" })

vim.keymap.del({ "n", "x" }, "gra", { silent = true })
vim.keymap.del("n", "grx", { silent = true })
vim.keymap.del("n", "gri", { silent = true })
vim.keymap.del("n", "grn", { silent = true })
vim.keymap.del("n", "grr", { silent = true })
vim.keymap.del("n", "grt", { silent = true })

vim.keymap.set({ 'i', 'c' }, '<C-j>', [[pumvisible() ? "\<C-n>" : "\<C-j>"]], { expr = true })
vim.keymap.set({ 'i', 'c' }, '<C-k>', [[pumvisible() ? "\<C-p>" : "\<C-k>"]], { expr = true })
vim.keymap.set({ 'i', 'c' }, '<C-l>', [[pumvisible() ? "\<C-y>" : "\<C-l>"]], { expr = true })
