local opt = vim.opt

opt.tabclose = "uselast"                                                                                           -- go to last used tab when closing the current tab
opt.backspace = vim.list_extend(vim.opt.backspace:get(), { "nostop" })                                             -- don't stop backspace at insert
opt.breakindent = true                                                                                             -- wrap indent to match  line start
opt.clipboard = "unnamedplus"                                                                                      -- connection to the system clipboard
opt.cmdheight = 0                                                                                                  -- hide command line unless needed
opt.completeopt = { "menu", "menuone", "noselect" }                                                                -- Options for insert mode completion
opt.confirm = true                                                                                                 -- raise a dialog asking if you wish to save the current file(s)
opt.copyindent = true                                                                                              -- copy the previous indentation on autoindenting
opt.cursorline = false                                                                                             -- highlight the text line of the cursor
opt.diffopt = vim.list_extend(vim.opt.diffopt:get(), { "algorithm:histogram", "linematch:60" })                    -- enable linematch diff algorithm
opt.expandtab = true                                                                                               -- enable the use of space in tab
opt.fillchars = { eob = " " }                                                                                      -- disable `~` on nonexistent lines
opt.ignorecase = true                                                                                              -- case insensitive searching
opt.infercase = true                                                                                               -- infer cases in keyword completion
opt.jumpoptions = {}                                                                                               -- apply no jumpoptions on startup
opt.laststatus = 3                                                                                                 -- global statusline
opt.linebreak = true                                                                                               -- wrap lines at 'breakat'
opt.mouse = "a"                                                                                                    -- enable mouse support
opt.number = true                                                                                                  -- show numberline
opt.preserveindent = true                                                                                          -- preserve indent structure as much as possible
opt.pumheight = 10                                                                                                 -- height of the pop up menu
opt.relativenumber = true                                                                                          -- show relative numberline
opt.shiftround = true                                                                                              -- round indentation with `>`/`<` to shiftwidth
opt.shiftwidth = 2                                                                                                 -- number of space inserted for indentation; when zero the 'tabstop' value will be used
opt.softtabstop = 2                                                                                                -- Soft tab stop
opt.shortmess = vim.tbl_deep_extend("force", vim.opt.shortmess:get(), { s = true, I = false, c = true, C = true }) -- disable search count wrap, startup messages, and completion messages
opt.showmode = false                                                                                               -- disable showing modes in command line
opt.signcolumn = "yes"                                                                                             -- always show the sign column
opt.smartcase = true                                                                                               -- case sensitive searching
opt.hlsearch = true                                                                                                -- highlight search results
opt.smarttab = true                                                                                                -- Smart tab
opt.smartindent = true                                                                                             -- Make indenting smart
opt.splitbelow = true                                                                                              -- splitting a new window below the current one
opt.splitright = true                                                                                              -- splitting a new window at the right of the current one
opt.tabstop = 2                                                                                                    -- number of space in a tab
opt.timeout = false                                                                                                -- shorten key timeout length a little bit for which-key
opt.title = true                                                                                                   -- set terminal title to the filename and path
opt.undofile = true                                                                                                -- enable persistent undo
opt.updatetime = 250                                                                                               -- length of time to wait before triggering the plugin
opt.virtualedit = "block"                                                                                          -- allow going past end of line in visual block mode
opt.wrap = false                                                                                                   -- disable wrapping of lines longer than the width of window
opt.writebackup = false                                                                                            -- disable making a backup before overwriting a file
opt.inccommand = "split"                                                                                           -- incremental search
opt.scrolloff = 999                                                                                                -- scrolloff 999
opt.sidescrolloff = 8                                                                                              -- sidescrolloff 8
opt.grepprg = "rg --vimgrep --smart-case"                                                                          -- grepprg
opt.lazyredraw = false                                                                                             -- lazyredraw
opt.errorbells = false                                                                                             -- Disable error sounds
opt.autochdir = false                                                                                              -- Don't change directory automatically
opt.swapfile = false                                                                                               -- Don't create swapfile
opt.backup = false                                                                                                 -- Don't create backup
opt.background = "dark"                                                                                            -- Set background to dark
opt.foldenable = true                                                                                              -- Enable folding
opt.foldlevel = 99                                                                                                 -- Set foldlevel to 99
opt.foldlevelstart = 99                                                                                            -- Set foldlevelstart to 99
opt.foldmethod = "expr"                                                                                            -- Set foldmethod to expr
opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"                                                                   -- Set foldexpr to treesitter foldexpr
opt.winborder = "rounded"                                                                                          -- Set winborder to rounded
opt.guicursor = "n-v-c-i:block"                                                                                    -- Set guicursor to block
opt.termguicolors = true                                                                                           -- Set termguicolors to true
