local M = {}

M.symbol_icons = {
  Array = "",
  Boolean = "󰨙",
  Class = "󰯳",
  Color = "󰰠",
  Control = "",
  Collapsed = ">",
  Constant = "󰯱",
  Constructor = "",
  Enum = "󰯹",
  EnumMember = "",
  Event = "",
  Field = "",
  File = "",
  Folder = "",
  Function = "󰡱",
  Interface = "󰰅",
  Key = "",
  Keyword = "󱕴",
  Method = "󰰑",
  Module = "󰆼",
  Namespace = "󰰔",
  Null = "",
  Number = "",
  Object = "󰲟",
  Operator = "",
  Package = "󰰚",
  Property = "󰲽",
  Reference = "󰰠",
  Snippet = "",
  String = "",
  Struct = "󰰣",
  Text = "󱜥",
  TypeParameter = "󰰦",
  Unit = "󱜥",
  Value = "",
  Variable = "󰫧",
}

return M
